### ISSUE TITLE
在 safari 上结合油猴无法正常使用

### ISSUE THREAD

**Issue by HerrHuang** [Kenshin/simpread-little#5]
macOS 13.1 (22C65) Intel芯片

**Comment by Kenshin** [comment]
嗨，已经不建议使用油猴脚本了，会有 Safari 版的。

**Comment by Kenshin** [comment]
油猴脚本仅仅只是 1.x 部分功能而已。

**Comment by steveshi** [comment]
一直用safari做主力浏览器，然而简阅一直没有适配，同步助手2023年更新还是Intel only……
