### ISSUE TITLE
能否恢复油猴脚本

### ISSUE THREAD

**Issue by alphavvv** [Kenshin/simpread-little#7]
目前无法正常使用

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简悦。

油猴脚本只是 1.x 的部分功能，跟目前的功能差别太大了，所以暂时不会重新上架它。

**Comment by alphavvv** [comment]
> 嗨，谢谢喜欢简悦。
> 
> 
> 
> 油猴脚本只是 1.x 的部分功能，跟目前的功能差别太大了，所以暂时不会重新上架它。

感谢回复 那移动端想要使用还有什么好的方案吗 请问safari扩展还有计划推出吗

**Comment by Kenshin** [comment]
会推出 Safari 原生扩展的 😄
